// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NSpace: typeof import('naive-ui')['NSpace']
}
export {}
